tuirer/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from core.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),

    path('', include('tuites.urls')),
    path('', include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tuites/urls.py
# URLs de tuites
from django.urls import path
from tuites.views import PostTuiteView, LikeTuiteView

app_name = 'tuites'

urlpatterns = [
    path('postar/', PostTuiteView.as_view(), name="post_tuite"),
    path('like/<int:pk>/', LikeTuiteView.as_view(), name="like"),
]

users/urls.py
# URLs de users
from django.urls import path
from users.views import (
    ProfileEditView,
    ProfileView,
    UserLoginView,
    UserLogoutView,
    UserSignupView,
    UserFollowView,
)

app_name = 'users'

urlpatterns = [
    # indica o tipo e a variável
    # pk do model que será carregado na view passada
    path('perfil/<int:pk>/', ProfileView.as_view(), name='profile'),
    path('perfil/<int:pk>/editar/', ProfileEditView.as_view(), name='profile-edit'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('cadastro/', UserSignupView.as_view(), name='signup'),
    path('seguir/<int:pk>/', UserFollowView.as_view(), name='follow'),
]

core/models.py
from django.db import models

# Create your models here.

tuites/models.py
from django.db import models
from tuites.managers import TuitesManager


class Tuite(models.Model):
    content = models.CharField('Tuite', max_length=280)
    #author = models.ForeignKey('users.User', verbose_name='Autor', on_delete=models.CASCADE, related_name='tuites')
    author = models.ForeignKey('users.User', verbose_name='Autor', default=1, on_delete=models.SET_DEFAULT, related_name='tuites')
    date_created = models.DateTimeField(auto_now_add=True)
    liked_by = models.ManyToManyField('users.User', blank=True)

    # sobrescrevendo a classe default objects
    objects = TuitesManager()

    @property
    def likes_count(self):
        return self.liked_by.count()

    def get_author_username(self):
        return self.author.username

    def __str__(self):
        return f'{self.author.username}: {self.content}'

    class Meta:
        # no painel, está ordenando os tuites pelo content (alfabeticamente por default)
        ordering = ('content', )

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.
class User(AbstractUser):
    picture = models.ImageField('Foto de perfil', default='img/blank-pic.png')
    following = models.ManyToManyField('self', related_name='following_users', blank=True, symmetrical=False)
    followers = models.ManyToManyField('self', blank=True, symmetrical=False)

    @property
    def following_count(self):
        return self.following.count()
    
    @property
    def followers_count(self):
        return self.followers.count()

tuites/forms.py
from django import forms

from tuites.models import Tuite


class PostTuiteForm(forms.ModelForm):
    class Meta:
        model = Tuite
        fields = ('content', 'author')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['author'].initial = self.initial['user'].id
        self.fields['author'].widget = forms.HiddenInput()
        self.fields['content'].help_text = 'Digite o que vocês está pensando aqui'
        # self.fields['content'].widget = forms.TextInput(attrs={'class': 'post-tuite-input'})

    def clean(self):
        cleaned_data = super().clean()
        content = self.cleaned_data.get('content')
        
        if 'Temer' in content:
            raise forms.ValidationError('FORA TEMER')

        if not self.initial.get('user') == cleaned_data.get('author'):
            raise forms.ValidationError('Não tente burlar o sistema!')

        return cleaned_data

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from users.models import User


class UserSignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email')

    def clean_email(self):
        email = self.cleaned_data.get('email')
        user_exists = User.objects.filter(email=email).exists()
        if user_exists:
            raise forms.ValidationError('Um usuário com este e-mail já existe!')
        return email

core/views.py
from datetime import datetime

from django.http import HttpResponse
from django.shortcuts import render

from tuites.models import Tuite


def index(request):
    context = {
        "now": datetime.now(),
        'tuites': Tuite.objects.all().order_by('-date_created'),
        # 'tuites': Tuite.objects.search('opa'),
    }

    return render(request, 'home.html', context)

tuites/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, RedirectView

from tuites.forms import PostTuiteForm
from tuites.models import Tuite


class PostTuiteView(LoginRequiredMixin, CreateView):
    model = Tuite
    template_name = 'post_tuite.html'
    form_class = PostTuiteForm
    # reverse_lazy só será chamado 
    success_url = reverse_lazy('tuites:post_tuite')

    def get_initial(self):
        return {
            'user': self.request.user
        }

    # https://docs.djangoproject.com/en/2.0/ref/contrib/messages/
    def form_valid(self, form):
        messages.success (
            self.request,
            'Você postou um tuite!'
        )
        return super().form_valid(form)


class LikeTuiteView(RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        from_url = self.request.META.get('HTTP_REFERER')
        tuite_pk = kwargs.get('pk')
        user = self.request.user

        if not user.pk:
            return from_url
        
        tuite = Tuite.objects.get(pk=tuite_pk)
        # como o model é manytomany, podemos ter o filtro seguinte:
        if tuite.liked_by.filter(pk=user.pk).exists():
            tuite.liked_by.remove(user)
        else:
            tuite.liked_by.add(user)

        return f'{from_url}#{tuite_pk}'

users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import reverse_lazy
# updateview --> usada para editar um model que já existe
from django.views.generic import (CreateView, DetailView, RedirectView,
                                  UpdateView)

from users.forms import UserCreationForm, UserSignupForm
from users.mixins import ProfileAccessMixin
from users.models import User

# https://docs.djangoproject.com/en/2.0/ref/class-based-views/generic-display/#detailview
# a ordem dos Mixins importa. o quanto antes, maior a importância

# o que for referente a CRUD, geralmente vai pedir um formulário


class ProfileView(DetailView):
    model = User
    template_name = 'profile.html'
    # alteramos o nome que chamaremos o model no template a partir do context_object_name
    context_object_name = 'profile'


class ProfileEditView(ProfileAccessMixin, UpdateView):
    model = User
    fields = ('picture', 'username')
    template_name = 'profile_edit.html'
    # success_url = reverse_lazy('profile')
    # aqui não temos acesso a pk para redirecionar para o perfil
    # então, iremos sobrescrever um método
    
    def get_success_url(self):
        return reverse_lazy('users:profile', args=[self.object.pk])


class UserLoginView(LoginView):
    template_name = 'login.html'
    redirect_authenticated_user = True


class UserLogoutView(LogoutView):
    pass


class UserSignupView(CreateView):
    model = User
    form_class = UserSignupForm
    template_name = 'signup.html'
    success_url = reverse_lazy('tuites:post_tuite')


class UserFollowView(LoginRequiredMixin, RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        profile_pk = kwargs.get('pk')
        profile = User.objects.get(pk=profile_pk)
        request_user = self.request.user
        request_user_has_followed = request_user.following.filter(pk=profile_pk).exists()
        # import ipdb ; ipdb.set_trace()
        
        # caso o user logado siga o perfil
        if request_user_has_followed:
            request_user.following.remove(profile)
            profile.followers.remove(request_user)
        # caso o user logado não siga o perfil
        else:
            request_user.following.add(profile)
            profile.followers.add(request_user)
        
        return reverse_lazy('users:profile', args=[profile_pk])

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://fonts.googleapis.com/css?family=Raleway:400,500,600,600i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Quicksand:400,500,700" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ"
        crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="icon" type="image/png" href="{% static 'icon/fav-icon.png' %}">
    <title>Tuirer</title>
</head>

<body>
    <div class="navbar">
        <div class="navbar-title">
            <img src="{% static 'icon/icon.png' %}">
            <span>Tuirer</span>
        </div>
    </div>

    {% include "includes/menu.html" %} {% block body %} {% endblock %}

    <footer class="footer">
        <div class="footer-copyright">
            Copyright @ 2018
        </div>
        <div class="footer-made">
            Made with
            <i class="fas fa-code"></i>
            and
            <i class="far fa-heart"></i>
            by Pamella Bezerra
        </div>
    </footer>

</body>

</html>

templates/home.html
{% extends "base.html" %}

{% block body %}

    {% include "includes/message.html" %}

    <div class="cards">
        {% if request.user.is_authenticated %}
            {% for tuite in tuites %}
            {% include 'includes/card.html' %}
        {% endfor %}
        {% else %}
            {% for tuite in tuites|slice:":5" %}
                {% include 'includes/card.html' %}
            {% endfor %}
        {% endif %}
    </div>

{% endblock %}

templates/includes/card.html
{% load tuite_likes %}

<div class="card">
    <p class="content">{{ tuite.content }}</p>
    <hr>
    <div class="author-and-date">
        <a href="{% url 'users:profile' tuite.author.pk %}" class="author"> <!-- Adiciona link para o perfil do usuário -->
            <div class="author-avatar" style="background-image: url('{{ tuite.author.picture.url }}');"></div>
            @{{ tuite.author }} 
        </a>
        <span class="date">{{ tuite.date_created }}</span>
    </div>
    <div class="likes">
        <p>
            Curtido por
            {% for user_liked in tuite.liked_by.all %}
                {{ user_liked }}
            {% empty %}
                ninguém
            {% endfor %}
        </p>
        <div>
            <a href="{% url 'tuites:like' tuite.pk %}" class="likes-icon">
                {% tuite_liked_icon %}
                {{ tuite.likes_count }}
            </a>
        </div>
    </div>
    </a>
</div>

templates/includes/menu.html
<nav class="menu">
    <a class="menu__link" href="{% url 'index' %}">Início</a>
    <a class="menu__link" href="{% url 'tuites:post_tuite' %}">Postar Tuite</a>
    {% if request.user.is_authenticated %}
        <a class="menu__link" href="{% url 'users:profile' request.user.pk %}" class="redirect">Olá, <b>{{ user.username }}</b></a>
        <a class="menu__link" href="{% url 'users:logout' %}">Sair</a>
    {% else %}
        <a class="menu__link" href="{% url 'users:login' %}">Entrar</a>
        <a class="menu__link" href="{% url 'users:signup' %}">Cadastro</a>
    {% endif %}
</nav>

templates/includes/message.html
{% if messages %}
        {% for message in messages %}
            <div>{{ message }}</div>
        {% endfor %}
    {% endif %}

templates/login.html
{% extends "base.html" %}

{% block body %}

    <div class="login">
        <div class="login__title">Login</div>
        <form class="login-form" method="POST">
            {% csrf_token %}
            {{ form.as_p }}

            <input class="button" type="submit" value="Enviar">
        </form>
    </div>


{% endblock body %}

templates/post_tuite.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block body %}
    <div class="post-tuite">
        <div class="post-tuite__title">Postar tuite</div>

        {% if form.errors %}
            {% for error in form.non_field_errors %}
                <p> {{ error }} </p>
            {% endfor %}
        {% endif %}
    
        {% if messages %}
            {% for message in messages %}
                <p style="background-color: green" class="message">{{ message }}</p>
            {% endfor %}
        {% endif %}
        
        <form class="post-tuite-form" method="POST">
            {% csrf_token %}
    
            {% for field in form %}
                <div>
                    {% if not field.name == 'author' %}
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {% endif %}
        
                    {% render_field field class="post-tuite-field" placeholder=field.label autofocus=True %}
                    <p>{{ field.help_text }}</p>
                    {{ field.errors }}
                </div>
            {% endfor %}
            
            <input class="button" type="submit" value="Postar tuite">
        </form>

    </div>

{% endblock %}

templates/profile.html
{% extends "base.html" %}
{% load user_follow %}

{% block body %}
    <div class="profile">
        <div class="profile-header">
            {% if profile == request.user %}
                <p class="your-profile-warning">
                    Olá, <b>{{ user.username }}</b>, você está visualizando o seu perfil! 
                </p>
                <span>
                    Se quiser,
                    <a href="{% url 'users:profile-edit' request.user.pk %}" class="profile-edit">edite seu perfil aqui</a>
                </span>
            {% endif %}
            
            <div class="profile-info-box">
                <div class="profile-picture" style="background-image: url('{{ profile.picture.url }}');"></div>
                
                <div class="profile-info-content">
                    <div class="row">
                        <h2 class="username"> {{ profile.username }} </h2>  
                        <span class="email"> ({{ profile.email }})</span>
                    </div>
                    {% if profile != request.user %}
                        <div class="row">
                            <a href="{% url 'users:follow' profile.pk %}" class="follow">
                                {% follow %}
                            </a>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>

        <div class="profile-follow">

            <p class="title">Seguindo ({{ profile.following_count }})</p>
            {% if profile.following_count > 0 %}
                <div class="follow-list">
                    {% for following in profile.following.all %}
                        <a href="{% url 'users:profile' following.pk %}" class="follow-card">
                            <div class="avatar" style="background-image: url('{{ following.picture.url }}');"></div>
                            {{ following.username }}
                        </a>
                    {% endfor %}
                </div>
            {% endif %}

            <p class="title">Seguidores ({{ profile.followers_count }})</p>
            {% if profile.followers_count > 0 %}
                <div class="follow-list">
                    {% for follower in profile.followers.all %}
                        <a href="{% url 'users:profile' follower.pk %}" class="follow-card">
                            <div class="avatar" style="background-image: url('{{ follower.picture.url }}');"></div>
                            {{ follower.username }}
                        </a>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
        
        <div class="profile-tuites">
            {% for tuite in profile.tuites.all %}
                {% include "includes/card.html" %}
            {% endfor %}
        </div>
    </div>
{% endblock body %}

templates/profile_edit.html
{% extends "base.html" %}

{% block body %}
    
    <a href="{% url 'users:profile' request.user.pk %}">Voltar para seu perfil</a>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Enviar">
    </form>

{% endblock body %}

templates/signup.html
{% extends 'base.html' %}

{% block body %}
    <div class="signup">
        <div class="signup__title">Cadastro</div>
        <form class="signup-form" method="post">
            {% csrf_token %}
            {{ form.as_p }}

            <input class="button" type="submit" value="Registrar">
        </form>
    </div>
{% endblock %}